// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderAuthStrategy } from "./ModelProviderAuthStrategy";
import type { ModelProviderCredentialState } from "./ModelProviderCredentialState";
import type { ModelProviderKind } from "./ModelProviderKind";
import type { ModelProviderWireApi } from "./ModelProviderWireApi";

export type ModelProviderEntry = { id: string, displayName: string, description: string, kind: ModelProviderKind, wireApi: ModelProviderWireApi, authStrategy: ModelProviderAuthStrategy, selected: boolean, configured: boolean, selectable: boolean, disabledReason: string | null, defaultModel: string | null, credentialState?: ModelProviderCredentialState | null, setupHint?: string | null, };
