// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderEntry } from "./ModelProviderEntry";
import type { ModelProviderSelection } from "./ModelProviderSelection";

export type ModelProviderSelectResponse = { provider: ModelProviderEntry, selectedProvider: ModelProviderSelection, model: string | null, };
