#![allow(clippy::result_large_err)]
mod amazon_bedrock;
mod auth;
mod bearer_auth_provider;
mod identity;
mod models_endpoint;
mod provider;
mod provider_catalog;

pub use auth::auth_provider_from_auth;
pub use auth::unauthenticated_auth_provider;
pub use bearer_auth_provider::BearerAuthProvider;
pub use bearer_auth_provider::BearerAuthProvider as CoreAuthProvider;
pub use codex_protocol::account::ProviderAccount;
pub use identity::normalize_model_info;
pub use identity::normalize_model_instructions_text;
pub use identity::normalize_persisted_base_instructions;
pub use provider::ModelProvider;
pub use provider::ProviderAccountError;
pub use provider::ProviderAccountResult;
pub use provider::ProviderAccountState;
pub use provider::ProviderCapabilities;
pub use provider::RuntimeWireApi;
pub use provider::SharedModelProvider;
pub use provider::api_provider_from_info;
pub use provider::create_model_provider;
pub use provider_catalog::ANTHROPIC_API_KEY_ENV_VAR;
pub use provider_catalog::ANTHROPIC_DEFAULT_BASE_URL;
pub use provider_catalog::ANTHROPIC_DEFAULT_MODEL;
pub use provider_catalog::ANTHROPIC_PROVIDER_ID;
pub use provider_catalog::ANTHROPIC_PROVIDER_NAME;
pub use provider_catalog::LMSTUDIO_DEFAULT_MODEL;
pub use provider_catalog::OLLAMA_DEFAULT_MODEL;
pub use provider_catalog::OPENAI_DEFAULT_MODEL;
pub use provider_catalog::ProviderAuthStrategy;
pub use provider_catalog::ProviderCatalogEntry;
pub use provider_catalog::ProviderKind;
pub use provider_catalog::ProviderWireApi;
pub use provider_catalog::add_peregrine_builtin_model_providers;
pub use provider_catalog::create_anthropic_provider;
pub use provider_catalog::default_model_for_provider;
pub use provider_catalog::is_anthropic_provider_info;
pub use provider_catalog::provider_catalog_entries;
pub use provider_catalog::provider_catalog_entry_for_id;
